export const actionTypes = {
	FOLLOWER_LOAD_INIT: 'FOLLOW.FOLLOWER.LOAD.INIT',
	FOLLOWER_LOAD_DONE: 'FOLLOW.FOLLOWER.LOAD.DONE',
	FOLLOWER_LOAD_ERROR: 'FOLLOW.FOLLOWER.LOAD.ERROR',
	FOLLOWING_LOAD_INIT: 'FOLLOW.FOLLOWING.LOAD.INIT',
	FOLLOWING_LOAD_DONE: 'FOLLOW.FOLLOWING.LOAD.DONE',
	FOLLOWING_LOAD_ERROR: 'FOLLOW.FOLLOWING.LOAD.ERROR',
	FOLLOW_INIT: 'FOLLOW.FOLLOW.INIT',
	FOLLOW_DONE: 'FOLLOW.FOLLOW.DONE',
	FOLLOW_ERROR: 'FOLLOW.FOLLOW.ERROR',
};
